### ISSUE TITLE
Zpětná vazba No. 1

### ISSUE THREAD

**Issue by JanaNovotna** [Justisedli/zivotopis#1]
Ahoj! 

posílám první zpětnou vazbu, omlouvám se, že je to až teď. 

Mám několik poznámek na příště: 
- požíváš elementy main, header, section, footer... to je super, jen mám poznámku k pořadí: 
První je header 
Druhý je main
V rámci main jsou section  
Pak končí main a je footer
Je to spíš logický zápis jednotlivých elementů. 

Ale jinak je to pěkné a jen tak dál :) 

Janča

**Comment by Justisedli** [comment]
Ahoj, moc děkuji, pokusím si v tom udělat pořádek. 
Justina
